# Generated by Django 4.1.7 on 2023-03-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', models.ManyToManyField(blank=True, null=True, related_name='school', to='info.address')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='human/%Y/%d/%m')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.PositiveBigIntegerField(default=1234567890, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('married', models.CharField(choices=[('M', 'Married'), ('U', 'Unmarried')], default='U', max_length=1)),
                ('alien', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('address', models.ManyToManyField(related_name='human', to='info.address')),
                ('school', models.ManyToManyField(related_name='human', to='human.school')),
            ],
            options={
                'verbose_name': 'human',
                'ordering': ['username'],
                'get_latest_by': '-created',
            },
        ),
    ]
